#!/usr/bin/env python3
"""Update README coverage badge from coverage.py JSON output."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console

from xapp_tools.console import print_error
from xapp_tools.console import print_info
from xapp_tools.console import print_success
from xapp_tools.project_meta import resolve_package_metadata

BADGE_PATTERN = re.compile(
    r"!\[Coverage\]\(https://img\.shields\.io/badge/coverage-[^)]+\)"
)
BRIGHTGREEN_THRESHOLD = 90
GREEN_THRESHOLD = 80
YELLOWGREEN_THRESHOLD = 70
YELLOW_THRESHOLD = 60
ORANGE_THRESHOLD = 50


def badge_color(percent: int) -> str:
    if percent >= BRIGHTGREEN_THRESHOLD:
        return "brightgreen"
    if percent >= GREEN_THRESHOLD:
        return "green"
    if percent >= YELLOWGREEN_THRESHOLD:
        return "yellowgreen"
    if percent >= YELLOW_THRESHOLD:
        return "yellow"
    if percent >= ORANGE_THRESHOLD:
        return "orange"
    return "red"


def parse_coverage_percent(coverage_json: Path) -> float:
    data = json.loads(coverage_json.read_text(encoding="utf-8"))
    total = data.get("totals", {})
    percent_value = total.get("percent_covered")
    if not isinstance(percent_value, int | float):
        msg = f"Could not read totals.percent_covered from {coverage_json}"
        raise TypeError(msg)
    return round(percent_value, 2)


def render_badge(percent: float) -> str:
    color = badge_color(percent)
    return f"![Coverage](https://img.shields.io/badge/coverage-{percent}%25-{color})"


def update_readme(readme_path: Path, badge_markdown: str) -> bool:
    content = readme_path.read_text(encoding="utf-8")
    match = BADGE_PATTERN.search(content)

    if match:
        updated = BADGE_PATTERN.sub(badge_markdown, content, count=1)
    else:
        lines = content.splitlines()
        if not lines:
            msg = f"README is empty: {readme_path}"
            raise ValueError(msg)
        lines.insert(1, badge_markdown)
        updated = "\n".join(lines) + "\n"

    if updated == content:
        return False

    readme_path.write_text(updated, encoding="utf-8")
    return True


@click.command("coverage-badge")
@click.option(
    "--coverage-json",
    default="coverage.json",
    show_default=True,
    help="Path to coverage JSON generated by coverage.py/pytest-cov.",
)
@click.option(
    "--readme",
    default="README.md",
    show_default=True,
    help="Path to README file containing coverage badge.",
)
def main(coverage_json: str, readme: str) -> None:
    """Update README coverage badge from coverage.py JSON output."""
    # Get import package dir (e.g. xapp_tools) for --cov, not distribution name
    _, package_dir, _ = resolve_package_metadata()

    # Use absolute path for coverage.json
    # coverage_path = Path(coverage_json).absolute()
    # readme_path = Path(readme).absolute()
    coverage_path = Path(coverage_json)
    readme_path = Path(readme)

    # Run pytest with coverage, specifying output file location
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        "-q",
        f"--cov={package_dir}",
        "--cov-report=json",
    ]
    print_info(f"[cyan]Running:[/cyan] {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)  # noqa: PLW1510, S603
    if result.returncode != 0:
        print_error(f"pytest failed:\n{result.stdout}\n{result.stderr}")
        sys.exit(result.returncode)

    percent = parse_coverage_percent(coverage_path)
    badge = render_badge(percent)
    changed = update_readme(readme_path, badge)

    if changed:
        print_success(f"Updated README coverage badge to {percent}%")
    else:
        print_success(f"README coverage badge already up to date at {percent}%")

    if coverage_path.exists():
        coverage_path.unlink()


if __name__ == "__main__":
    main()
